version: '3.4'
services:
  database-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_USER}
    volumes:
      - database-postgres:/var/lib/postgresql/data

volumes:
  database-postgres:
